### PR TITLE
Play nice in supervision trees

### PR DESCRIPTION
**Pull request by zacharyfox**

### CODE REVIEW

**Comment by ddosia** [comment]
Correct me if I am wrong, but as far as I can tell if process follows `gen_server` behaviour, and it implicitly does, this types of messages are handled by `gen_server`'s code.

https://github.com/erlang/otp/blob/maint/lib/stdlib/src/gen_server.erl#L403

**Comment by zacharyfox** [comment]
I'm not sure what you mean - amqp_network_connection isn't a gen_server.

**Comment by motobob** [comment]
@zacharyfox 1 it's a gen_server and 2 it does not fix anything due to not being match on PID in gen_server code.

I wonder which issue are you trying to solve here...
if that is about spurious network_connstion died with 'EXIT' in logs you might be interested in https://algithub.pd.alertlogic.net/defender/al_rmq/pull/11. that has the example log msgs.

**Comment by zacharyfox** [comment]
Well - it prevents the errors I'm seeing. But that's fine if you don't care. I'll use my own fork.

**Comment by motobob** [comment]
@zacharyfox as been explained in HC by Daniil and Nicholas, you just mask it and that's why you do not see it.
We do care a lot and that's why not push commits which make things worse.

**Comment by motobob** [comment]
@zacharyfox @ddosia the very root cause of this nasty stuff found in yet another hidden `process_flag(trap_exit, true)` in amqp_*...

**Pull request closed without merging**
